### ISSUE TITLE
Add chainer-DCGAN?

### ISSUE THREAD

**Issue by junh1024** [deeppomf/DeepLearningAnimePapers#4]
Under  "Anime Generation", you could add chainer-DCGAN.

chainer-DCGAN is a anime implementation of a non-anime paper. Even though the results look terrible, It was one of the first to do "Anime face Generation" (or at least the earliest I knew of) so it might be a good idea to add it. It has a unique feature: the definition of some staples via dimension sliders, so you can make a face more or less say, 'nagato yuki-like'

Paper: https://arxiv.org/abs/1511.06434 (by FB & indico)
Code: https://github.com/mattya/chainer-DCGAN
Implementation: http://mattya.github.io/chainer-DCGAN/

(I found it under the make-girls-moe technical report which you already have, there's also a few other GANs referenced in that paper )

Your choice ofc.

Also, this isn't CV, but there was an intredasting article about anime lexicon analysis from 2008? but I can't find it now.

**Comment by deeppomf** [comment]
Thanks, but I want this repo to be about more recent, state of the art results.
